project_id = "cdynmxdsmdpzbjzzhjkf"

[functions.audit-design]
verify_jwt = false

[functions.fetch-figma-frames]
verify_jwt = false

[functions.audit-functionality]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false
